name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1


    - name: Build Docker image
      run: docker build -t web .

    - name: Log in to Docker Hub
      run: docker login -u “money7777777” -p “dckr_pat_kVbrDAQcMDsV2aVdtYa6F4jmVC8” docker.io

    - name: Push Docker image
      run: docker push web:latest
